### ISSUE TITLE
Dockerfile `AS` keyword not highlighted

### ISSUE THREAD

**Issue by XVilka** [asbjornenge/Docker.tmbundle#30] opened 2019-08-16 10:55 UTC
It is used in a FROM construction to alias the name:
```Dockerfile
FROM alpine:edge AS builder
```
See https://docs.docker.com/engine/reference/builder/#from for the reference.

![image](https://user-images.githubusercontent.com/203261/63162387-fadbb780-c054-11e9-8c6a-349dbd6925d4.png)

See https://github.com/github/linguist/issues/4612

**Comment by blag** [comment] 2019-12-05 06:34
Duplicate of #15. Closing.

**Closed by blag** 2019-12-05 06:34 UTC
Labels: bug, duplicate, help wanted
